name: Run the tests

on:
  pull_request:
    branches: ['main', 'feature/**']

# Important: The workflow needs all the permissions below.
# These permissions are mainly need to post and update the status check and
# feedback comment on your PR. Meticulous won’t work without them.
permissions:
  actions: write
  checks: write
  contents: read
  discussions: write
  pull-requests: write
  statuses: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20.x with yarn cache
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'yarn'

      - name: Install yarn
        run: yarn install --frozen-lockfile

      - name: Start the server
        run: |
          yarn build
          yarn start &

      # - name: Install Playwright
      #   run: yarn playwright install

      # - name: Run the tests
      #   run: yarn run codeceptjs:headless --verbose

      - name: Serve project
        # 2. The sleep is often required to ensure your app is readily being served
        #    by the time the Meticulous tests start
        run: |
          yarn serve &
          sleep 5

      - name: Run Meticulous tests
        uses: alwaysmeticulous/report-diffs-action@v1
        with:
          api-token: ${{ secrets.METICULOUS_API_TOKEN }}
          # TODO: Update the port and protocol below to match your app's frontend
          app-url: 'http://localhost:3000/'

        env:
          CI: false
